### ISSUE TITLE
Send email verification if Facebook email is a Gmail email, so the user can sign in with both accounts

### ISSUE THREAD

**Issue by giorgio79** [the-meedu-app/flutter-facebook-auth#28]
If Facebook email is a Gmail email, the user will be unable to sign in with Facebook unleass they verify their FB Gmail email, 

Could the module send email verification if the Facebook email is gmail, and send email verificatoin?
More info: https://stackoverflow.com/a/63299674/422752
```
"In firebase, it is very important to verify user email account the first time they login with Facebook , by sending a verification email.

Once email is verified, you can login with both Facebook and Gmail if user is using @gmail.com as email address.

Facebook Login -> Click Link in Verification Email -> Gmail Login -> Facebook Login (OK)

Facebook Login -> Gmail Login -> Click Link in Verification Email -> Facebook Login (NOT OK)

If you did not verify the Facebook email before user logout and try to login with their gmail, you will not be able to login with Facebook again the moment they login with their gmail.

share  edit  follow  flag "
```

**Comment by the-meedu-app** [comment]
This is not issue because is not posible send an email using the Facebook skd, also you don't need verify the email address to login with firebase.  But if the user has the same email on Gmail and Facebook you can sign in with firebase using firebase But if you were logged before facebook and now you use Google firebase will change thw auth method to google. In your firebase console account you can enable create multiples account with the same domain
